service: fivecast
image: <%= ENV["FIVECAST_REGISTRY_USERNAME"] %>/fivecast

servers:
  web:
    - <%= ENV["FIVECAST_IP"] %>

<% if ENV["FIVECAST_HOST"].present? %>
proxy:
  ssl: true
  host:
    - <%= ENV["FIVECAST_HOST"] %>
  forward_headers: true
<% end %>

registry:
  username: <%= ENV["FIVECAST_REGISTRY_USERNAME"] %>
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "fivecast_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
